# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HMQDjPMtIFdSjFq4lKmqa4lGI8318xw
"""

email_text = "Hi, I want to know about your gym membership plans."

print(email_text)

email_text = "Hi, I want to know about your gym membership plans."

if "membership" in email_text.lower():
    print("Membership inquiry detected!")

email_text = "Hi, I want to know about your gym membership plans."

if "membership" in email_text.lower():

    reply = """
Hello,

Thank you for contacting Minimum Strength Gym.

For membership details, please contact us at:

📞 +91 9876543210

We would be happy to assist you.

Regards,
Minimum Strength Gym
"""

    print(reply)

email_text = "I there any personal training  ."

email = email_text.lower()

if "membership" in email or "join" in email or "pricing" in email:

    reply = """
Hello,

Thank you for contacting Minimum Strength Gym.

For membership details, please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

elif "trainer" in email or "personal training" in email:

    reply = """
Hello,

Thank you for contacting us as we do not have any coaches there is not personal training .

Please contact us at:
+91 9876543210

Our coaching team will assist you.

Regards,
Minimum Strength Gym
"""

else:

    reply = """
Hello,

Thank you for contacting Minimum Strength Gym.

Please call us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

print(reply)

def generate_reply(email_text):

    email = email_text.lower()

    if "membership" in email or "join" in email or "pricing" in email:

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

For membership details, please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    elif "trainer" in email or "personal training" in email:

        return """
Hello,

Thank you for your interest in Personal Training.

Please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    else:

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

Please call us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""


email_text = "I want to join your gym."

reply = generate_reply(email_text)

print(reply)

membership_keywords = [
    "membership",
    "join",
    "pricing",
    "fees",
    "plans"
]

email_text = "can i join the gym ."

email = email_text.lower()

for keyword in membership_keywords:
    if keyword in email:
        print("Membership inquiry detected!")
        break

membership_keywords = [
    "membership",
    "join",
    "pricing",
    "fees",
    "plans"
]

trainer_keywords = [
    "trainer",
    "personal training",
    "coach",
    "coaching"
]


def classify_email(email_text):

    email = email_text.lower()

    for keyword in membership_keywords:
        if keyword in email:
            return "membership"

    for keyword in trainer_keywords:
        if keyword in email:
            return "trainer"

    return "general"


email_text = "Do you offer personal training?"

category = classify_email(email_text)

print(category)

membership_keywords = [
    "membership",
    "join",
    "pricing",
    "fees",
    "plans"
]

trainer_keywords = [
    "trainer",
    "personal training",
    "coach",
    "coaching"
]


def classify_email(email_text):

    email = email_text.lower()

    for keyword in membership_keywords:
        if keyword in email:
            return "membership"

    for keyword in trainer_keywords:
        if keyword in email:
            return "trainer"

    return "general"


def generate_reply(category):

    if category == "membership":

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

For membership details, please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    elif category == "trainer":

        return """
Hello,

Thank you for your interest in Personal Training.

Please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    else:

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

Please call us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""


email_text = input("Enter the email text:")

category = classify_email(email_text)

reply = generate_reply(category)

print("\n----- EMAIL ANALYSIS -----")
print("Category:", category)

print("\n----- AUTO REPLY -----")
print(reply)

membership_keywords = [
    "membership",
    "join",
    "pricing",
    "fees",
    "plans"
]

trainer_keywords = [
    "trainer",
    "personal training",
    "coach",
    "coaching"
]


def classify_email(email_text):

    email = email_text.lower()

    for keyword in membership_keywords:
        if keyword in email:
            return "membership"

    for keyword in trainer_keywords:
        if keyword in email:
            return "trainer"

    return "general"


def generate_reply(category):

    if category == "membership":

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

For membership details, please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    elif category == "trainer":

        return """
Hello,

Thank you for your interest in Personal Training.

Please contact us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""

    else:

        return """
Hello,

Thank you for contacting Minimum Strength Gym.

Please call us at:
+91 9876543210

Regards,
Minimum Strength Gym
"""


print("===== GYM EMAIL AGENT =====")

email_text = input("Enter the email text: ")

category = classify_email(email_text)

reply = generate_reply(category)

print("\n----- EMAIL ANALYSIS -----")
print("Category:", category)

print("\n----- AUTO REPLY -----")
print(reply)